import { InventoryItem } from '../types/inventory';

export const demoUsers = [
  { id: '1', email: 'admin@inventory.com', password: 'admin123', name: 'Admin User', role: 'admin' as const },
  { id: '2', email: 'demo@inventory.com', password: 'demo123', name: 'Demo User', role: 'user' as const },
];

export const demoInventoryItems: InventoryItem[] = [
  {
    id: '1',
    name: 'Wireless Mouse',
    sku: 'WM-001',
    barcode: '1234567890123',
    category: 'Electronics',
    location: 'Aisle A - Shelf 1',
    quantity: 45,
    minQuantity: 20,
    price: 29.99,
    supplier: 'TechSupply Co.',
    expiryDate: undefined,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'USB-C Cable',
    sku: 'UC-002',
    barcode: '2345678901234',
    category: 'Accessories',
    location: 'Aisle B - Bin 4',
    quantity: 12,
    minQuantity: 30,
    price: 12.99,
    supplier: 'CableWorld',
    expiryDate: undefined,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Laptop Stand',
    sku: 'LS-003',
    barcode: '3456789012345',
    category: 'Furniture',
    location: 'Backroom - Rack 2',
    quantity: 78,
    minQuantity: 15,
    price: 49.99,
    supplier: 'Office Essentials',
    expiryDate: undefined,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Mechanical Keyboard',
    sku: 'MK-004',
    barcode: '4567890123456',
    category: 'Electronics',
    location: 'Aisle A - Shelf 3',
    quantity: 23,
    minQuantity: 10,
    price: 89.99,
    supplier: 'TechSupply Co.',
    expiryDate: undefined,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Monitor 27"',
    sku: 'MN-005',
    barcode: '5678901234567',
    category: 'Electronics',
    location: 'Warehouse - Pallet 7',
    quantity: 8,
    minQuantity: 15,
    price: 299.99,
    supplier: 'Display Depot',
    expiryDate: undefined,
    lastUpdated: new Date().toISOString(),
  },
];

export const defaultCategories = ['Electronics', 'Accessories', 'Furniture', 'Office Supplies', 'Other'];
